name: Deploy backend
on: [push]

jobs:
  Deploy-backend:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./backend/
    steps:
      - uses: actions/checkout@v3 # allow github action to work with your github repo
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
